### /health
GET http://localhost:4002/health

### create wallet /wallets
POST http://localhost:4002/wallets
Content-Type: application/json

{
  "playerId": "player-1",
  "currency": "BRL"
}

### get wallet by playerId /wallets/:playerId
GET http://localhost:4002/wallets/player-1

### create transaction /wallets/debit-bet
POST http://localhost:4002/wallets/debit-bet
Content-Type: application/json

{
  "playerId": "player-1",
  "operationId": "operation-1",
  "amountCents": "100",
  "referenceRoundId": "round-1",
  "referenceBetId": "bet-1"
}
