### /health
GET http://localhost:4002/health

### create wallet /wallets
POST http://localhost:4002/wallets
Content-Type: application/json

{
  "playerId": "player-rmq-1",
  "currency": "BRL"
}

### get wallet by playerId /wallets/:playerId
GET http://localhost:4002/wallets/player-rmq-1

### create transaction /wallets/debit-bet
POST http://localhost:4002/wallets/debit-bet
Content-Type: application/json

{
  "playerId": "player-rmq-1",
  "operationId": "operation-rmq-debit-1",
  "amountCents": "100",
  "referenceRoundId": "round-rmq-1",
  "referenceBetId": "bet-rmq-1"
}

### create transaction /wallets/credit-cashout
POST http://localhost:4002/wallets/credit-cashout
Content-Type: application/json

{
  "playerId": "player-rmq-1",
  "operationId": "operation-rmq-credit-1",
  "amountCents": "1000",
  "referenceRoundId": "round-rmq-1",
  "referenceBetId": "bet-rmq-1"
}
